### ISSUE TITLE
Embedded Binaries vs Link Frameworks and Libraries

### ISSUE THREAD

**Issue by onmyway133** [stepanhruda/dyld-image-loading-performance#5]
Hi, I very much like your research on this problem. I asked this http://stackoverflow.com/questions/34834717/what-are-the-libraries-linking-options-in-xcode on SO, but hope you can answer it.
1. Why don't you mention `Embedded Binaries` in this repo?
2. What does it mean by "share symbols instead of shipping them multiple times" 
   
   > plus frameworks allow you to share symbols instead of shipping them multiple times and inflating your bundle size.
3. You're talking about custom frameworks that the app depends, or system frameworks?
   
   > the image loading/linking time that dyld takes during first app launch is so long

Thanks in advance ☺️

**Comment by stepanhruda** [comment]
1. The example is a single app without extensions or any other targets, so I didn't mention embedding. It is implied, though. Keep in mind that "embedded" doesn't mean anything more than "copied into the Frameworks directory in the app bundle". Otherwise it wouldn't be possible to load them during the dynamic linking phase, where the problem existed.
2. If you want your extension and your app to have access to the same code, you either include that code in both the app and the extension (including it twice = additional binary size) or include it once in a third place that both have access to. This third place is a dynamically linked library or framework.
3. This radar was about custom frameworks. I haven't really investigated system frameworks – it's harder to link against that many of them and it sounds more dangerous to try and mess with linking of system frameworks.

**Comment by stepanhruda** [comment]
Did these answer your questions? If yes, I'll go ahead and close this issue.

**Comment by onmyway133** [comment]
@stepanhruda Yes, it is. Thanks very much
